"use client";

import { useState, useCallback } from "react";

interface UploadOptions {
  templateId?: string;
  allowedTypes?: string[];
  maxSizeMB?: number;
}

interface VideoUploadResult {
  url: string;
  isLocal: boolean;
  transloaditId?: string;
  originalName?: string;
  size?: number;
  mimeType?: string;
  duration?: number;
  status: "processing" | "completed" | "failed";
}

export function useTransloaditVideoUpload(options?: UploadOptions) {
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  const uploadFile = useCallback(
    async (file: File): Promise<VideoUploadResult | null> => {
      if (!file) return null;

      const fallbackTemplateId = options?.templateId;

      try {
        setIsUploading(true);
        setError(null);
        setUploadProgress(0);

        const fileExt = file.name.split(".").pop() || "";

        // First, get the signature from our API proxy
        const response = await fetch("/api/transloadit/signature", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            templateId: fallbackTemplateId,
            fileExt: fileExt,
            mimeType: file.type || undefined,
          }),
        });

        if (!response.ok) {
          throw new Error("Failed to get signature");
        }

        const signatureData = await response.json();

        // Prepare the upload form data
        const formData = new FormData();

        // When modifying the template ID on the frontend after a signature is generated on the backend,
        // it invalidates the cryptographic signature hash.
        // Therefore, we MUST use exactly the JSON string generated by the backend!
        let paramsString = signatureData.params;

        // Only if the backend somehow didn't stringify it do we do it here
        if (typeof paramsString !== "string") {
          paramsString = JSON.stringify(paramsString);
        }

        formData.append("params", paramsString);
        formData.append("signature", signatureData.signature);
        formData.append("file", file);

        return new Promise<VideoUploadResult>((resolve, reject) => {
          const xhr = new XMLHttpRequest();

          // Debugging network logs to pinpoint failure step precisely
          console.log(
            "🚀 Transloadit Network Start:",
            signatureData.endpoint || "https://api2.transloadit.com/assemblies",
          );

          // Always resolve dynamically bound endpoints or securely fallback
          const endpoint =
            signatureData.endpoint || "https://api2.transloadit.com/assemblies";

          xhr.upload.addEventListener("progress", (event) => {
            if (event.lengthComputable) {
              const percentComplete = Math.round(
                (event.loaded / event.total) * 100,
              );
              setUploadProgress(percentComplete);
            }
          });

          // Handle assembly polling logic to wait for processing to finish
          const pollAssemblyStatus = async (assemblyUrl: string) => {
            try {
              const res = await fetch(assemblyUrl);
              const data = await res.json();

              console.log(
                "🔄 Assembly Polling Step:",
                data.ok,
                data.bytes_received,
              );

              if (data.ok === "ASSEMBLY_COMPLETED") {
                setIsUploading(false);

                // Get the processed video (assuming it's in the first step's results)
                let processedVideo = null;
                let originalFile = data.uploads?.[0] || {
                  name: file.name,
                  size: file.size,
                  type: file.type,
                };

                // Flexible result finding
                if (data.results) {
                  for (const stepName in data.results) {
                    if (
                      data.results[stepName].length > 0 &&
                      (data.results[stepName][0].mime?.includes("video") ||
                        data.results[stepName][0].type === "video")
                    ) {
                      processedVideo = data.results[stepName][0];
                      console.log("✅ Found Video Result Step:", stepName);
                      break;
                    }
                  }

                  // Fallback if no specific video step found but results exist
                  if (!processedVideo) {
                    const firstStep = Object.keys(data.results)[0];
                    if (firstStep) processedVideo = data.results[firstStep][0];
                  }
                }

                if (processedVideo) {
                  // Final payload resolved cleanly
                  const finalVideoUrl =
                    processedVideo.ssl_url || processedVideo.url;
                  console.log("✅ Final Video Resolved:", finalVideoUrl);

                  resolve({
                    url: finalVideoUrl,
                    isLocal: false,
                    transloaditId: data.assembly_id,
                    originalName: originalFile.name,
                    size: processedVideo.size || originalFile.size,
                    mimeType:
                      processedVideo.mime || originalFile.type || "video/mp4",
                    duration: processedVideo.meta?.duration,
                    status: "completed",
                  });
                  return;
                } else if (originalFile?.url) {
                  // Fallback to exactly what we uploaded
                  resolve({
                    url: originalFile.ssl_url || originalFile.url,
                    isLocal: false,
                    transloaditId: data.assembly_id,
                    originalName: originalFile.name,
                    size: originalFile.size,
                    mimeType: originalFile.type || "video/mp4",
                    status: "completed",
                  });
                  return;
                }
              } else if (data.ok === "ASSEMBLY_ERROR" || data.error) {
                console.error("❌ Assembly failed during processing:", data);
                throw new Error(data.message || "Upload failed");
              }
            } catch (pollError: any) {
              console.error("Error polling assembly:", pollError);
              reject(new Error("Polling error: " + pollError.message));
            }
          };

          xhr.addEventListener("load", () => {
            console.log(
              "📡 Immediate Transloadit Response:",
              xhr.status,
              xhr.responseText,
            );

            if (xhr.status >= 200 && xhr.status < 300) {
              try {
                const response = JSON.parse(xhr.responseText);

                // If it's a direct upload (no encoding/processing required)
                if (response.ok === "ASSEMBLY_COMPLETED") {
                  const originalFile = response.uploads?.[0] || {
                    name: file.name,
                    size: file.size,
                    type: file.type,
                  };
                  let processedVideo = null;

                  if (response.results) {
                    const firstStep = Object.keys(response.results)[0];
                    if (firstStep)
                      processedVideo = response.results[firstStep][0];
                  }

                  if (processedVideo) {
                    const finalUrl =
                      processedVideo.ssl_url || processedVideo.url;
                    resolve({
                      url: finalUrl,
                      isLocal: false,
                      transloaditId: response.assembly_id,
                      originalName: originalFile.name,
                      size: processedVideo.size || originalFile.size,
                      mimeType:
                        processedVideo.mime || originalFile.type || "video/mp4",
                      duration: processedVideo.meta?.duration,
                      status: "completed",
                    });
                  } else if (originalFile?.url) {
                    resolve({
                      url: originalFile.ssl_url || originalFile.url,
                      isLocal: false,
                      transloaditId: response.assembly_id,
                      originalName: originalFile.name,
                      size: originalFile.size,
                      mimeType: originalFile.type || "video/mp4",
                      status: "completed",
                    });
                  } else {
                    reject(
                      new Error("Upload succeeded but no file URL returned"),
                    );
                  }
                }
                // If it's still executing (which happens explicitly with most Video templates)
                else if (response.assembly_ssl_url) {
                  console.log(
                    "⏱️ Assembly is executing. Polling URL:",
                    response.assembly_ssl_url,
                  );
                  pollAssemblyStatus(response.assembly_ssl_url);
                } else {
                  console.warn("⚠️ Unexpected response structure:", response);
                  reject(new Error("Unexpected Transloadit response format"));
                }
              } catch (parseError) {
                throw new Error("Failed to parse upload response");
              }
            } else {
              let errorMessage = `Upload failed with status ${xhr.status}`;
              try {
                const errorData = JSON.parse(xhr.responseText);
                console.error("❌ Transloadit Error Detail:", errorData);
                errorMessage =
                  errorData.message || errorData.error || errorMessage;
              } catch (e) {
                // Ignore parse errors for non-JSON responses
              }
              reject(new Error(errorMessage));
            }
          });

          xhr.addEventListener("error", (e) => {
            console.error("❌ XHR Network Error:", e);
            reject(new Error("Network error during upload"));
          });

          xhr.addEventListener("abort", () => {
            reject(new Error("Upload cancelled"));
          });

          xhr.open("POST", endpoint);
          xhr.send(formData);
        });
      } catch (err: any) {
        const errorMessage = err.message || "Upload failed";

        setIsUploading(false);
        setUploadProgress(0);
        setError(errorMessage);

        throw err;
      }
    },
    [],
  );

  const resetUpload = useCallback(() => {
    setIsUploading(false);
    setUploadProgress(0);
    setError(null);
  }, []);

  return {
    uploadFile,
    resetUpload,
    isUploading,
    uploadProgress,
    error,
  };
}
